### ISSUE TITLE
Improve package version detection using jq, python and node

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#107]
The following improvement made to the package section in spaceship should be ported over to spacefish to improve the accuracy of the version shown.

## 

> [🐟](https://github.com/matchai/spacefish-bot) **spacefish-bot** — Pull request copied from: https://github.com/denysdovhan/spaceship-prompt/pull/441.

`grep` solution to fetch version `package.json` was hacky and wasn't always returning expected values. Now using other fallback methods to get version information, Following discussions from denysdovhan/spaceship-prompt#439 

**Changes**

- Fetch version information with `jq` with fallback to `python` and `node`.
- Gracefully exit from the section if no version information is found or is `undefined` from `package.json`

Fix denysdovhan/spaceship-prompt#439 
Close denysdovhan/spaceship-prompt#552 
Close denysdovhan/spaceship-prompt#553

**Comment by tiffafoo** [comment]
This was done in #143 🎉
