### ISSUE TITLE
Fira Code font symbols missing in vscode windows 10

### ISSUE THREAD

**Issue by gertcuykens** [matchai/spacefish#118]
```json
{
    "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\fish.exe",
    "terminal.integrated.env.windows": {
        "MSYSTEM": "MSYS"
    },
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.fontFamily":"Fira Code",
    "editor.fontSize": 16,
    "editor.fontLigatures": true, 
    "editor.fontFamily":"Fira Code",
    "git.path": "C:\\git\\bin\\git.exe",
}
```
![image](https://user-images.githubusercontent.com/863731/49199852-53213b00-f39a-11e8-8aa5-f5806dbf97c5.png)

Also tried `Fira Mono for Powerline` but I can't seem to figure out how to display the last character in my case golang symbol

Second, In PowerShell terminal the arrow doesn't seem rendered correctly

![image](https://user-images.githubusercontent.com/863731/49201958-4228f780-f3a3-11e8-8152-836fb454fdc0.png)

**Comment by salmanulfarzy** [comment]
Fira Code was used for git branch symbol, Which is correctly rendered on VS Code. Go lang section use emoji and that's the one displayed as boxes. Windows have terrible support for Unicode symbols. 

I don't use Windows, So until any fellow Windows users are able to help, You could customize it with `SPACEFISH_GOLANG_SYMBOL`.

**Comment by gertcuykens** [comment]
Ok thx, what about the arrow in PowerShell is it also a emoji?

**Comment by matchai** [comment]
The arrow isn't an emoji, though it is in the UTF-8 character set. It looks like you have to enable UTF-8 explicitly in Powershell with `chcp 65001` ([details here](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell)).

**Comment by gertcuykens** [comment]
Can't believe windows still doesn't use UTF-8 by default...
Now I can see UTF-8 chracters that I type but arrow still seem to go trough something else.
![image](https://user-images.githubusercontent.com/863731/49232655-a7590900-f3f4-11e8-908e-0cd64f5b911c.png)

**Comment by matchai** [comment]
Are you using a powerline font as well in Powershell?

**Comment by gertcuykens** [comment]
Lets abandon the PowerShell for now because I have a feeling that thing is just legacy beyond imagination. If we would manage to get the vscode terminal working would be great, the reason I think it's still doable is that the editor itself has no emoji problem so it might be a terminal js problem but still think this can be fixed

![image](https://user-images.githubusercontent.com/863731/49242908-43dad580-f40c-11e8-9665-ba70813483d1.png)

**Comment by Snuggle** [comment]
Heya! :rainbow::sparkles: 

This doesn't exactly seem like an Spacefish-specific issue and I don't believe anyone here will be able to help other than upstream. (Best of luck with the issue you've replied to above!)

As @salmanulfarzy said earlier, if you have another symbol that works in the meantime that you'd like to use, you can add `set SPACEFISH_GOLANG_SYMBOL 🌮` to your `~/.config/fish/config.fish` to override the default arrow icon with a taco.

If you have any further topic-related questions, feel free to ask, but this issue should be closed and I'll add the appropriate tags. :two_hearts:
