### ISSUE TITLE
It doesn't wrap if the number of characters exceeds columns of terminal

### ISSUE THREAD

**Issue by smorimoto** [matchai/spacefish#123]
## Bug Report

**Current Behavior**

It doesn't wrap if the number of characters exceeds columns of terminal.

**Expected Behavior**

It should wrap like pure theme.

**Environment**

- Spacefish version: 1.10.3
- Fish version: fish, version 2.7.1
- Fish plugin manager: fisher
- Terminal emulator: iTerm, Terminal
- Operating system: macOS 10.14.1

**Additional context/Screenshots**

| Spacefish | Pure |
| :---------: | :---: |
| <img src="https://user-images.githubusercontent.com/38746192/49352301-a4af2a00-f6fa-11e8-841c-0dff2044c462.png"> | <img src="https://user-images.githubusercontent.com/38746192/49352316-af69bf00-f6fa-11e8-94f0-ef29a1bafbfe.png"> |

**Comment by Snuggle** [comment]
Interesting, two quick-questions to start:

Where does the Pure prompt implement this text wrapping? How many other terminal prompts wrap in a similar fashion?

**Comment by smorimoto** [comment]
Hi! Hmm... I really don't familiar with fish shell, so I couldn't find. and I've not checked other themes except Pure, but I can check the other ones when I have much time.

**Comment by Snuggle** [comment]
![image](https://user-images.githubusercontent.com/26250962/49373039-89412080-f6f4-11e8-83df-65bb99d2f0ad.png)

Is this what you're referring to?

**Comment by Snuggle** [comment]
Hm, I can reproduce & this causes some _incredibly_ weird behaviour. Typing `exit` exits the terminal emulator. I've seen this a couple of times before, but didn't know what caused it.

This completely breaks the prompt and I can't find a way to resolve it without reopening a new terminal instance.

![image](https://user-images.githubusercontent.com/26250962/49373335-a9251400-f6f5-11e8-84fc-4d3a8f98b92d.png)
![image](https://user-images.githubusercontent.com/26250962/49373350-b3471280-f6f5-11e8-8103-4fd9376687e7.png)

**Comment by Snuggle** [comment]
This issue doesn't occur if all the sections _(Except char)_ are removed. This reduces the problem to one within a section somewhere. When I have some free time, I can try and figure out which section is causing this bug through elimination.

![image](https://user-images.githubusercontent.com/26250962/49374299-d4f5c900-f6f8-11e8-983b-4b26e496743a.png)

**Comment by matchai** [comment]
This is actually deliberate behavior in fish: https://github.com/fish-shell/fish-shell/issues/904#issuecomment-21162556
There has been a proposal in a past issue to identify when text wraps and to dynamically shorten or split the prompt based on the width of the terminal. I'd consider it if that's what zsh does natively.

**Comment by Snuggle** [comment]
It completely breaks the fish instance though? Commands like `ls` stop working entirely afterwards?

**Comment by matchai** [comment]
Oof. Yeah, didn't expect that to happen. 😰
Unfortunately, this still appears to be an upstream issue, being able to reproduce it without spacefish installed:
![image](https://user-images.githubusercontent.com/4658208/49383839-ade2cb80-f6e7-11e8-9fff-44a8259f9370.png)

**Comment by Snuggle** [comment]
Is there a workaround we could make to get around this issue? I've had it myself a few times and just ended up opening a new terminal instance instead.

**Comment by matchai** [comment]
I think anything we end up doing here would be hacky and this would best be addressed by the fish team, unless we decide to make the theme dynamically resizing based on `$COLUMNS`.

Closing this as it's not an issue in spacefish, but feel free to keep the conversation going. 😄
