### ISSUE TITLE
Prompt does not work on light color themes

### ISSUE THREAD

**Issue by ohcibi** [matchai/spacefish#132]
## Bug Report

**Current Behavior**
The prefix/suffix strings are not visible on a light background

**Expected Behavior**
Documentation and/or default setup should respect dark AND light color themes

**Comment by matchai** [comment]
Hey @ohcibi Thank you for opening an issue!

Gah! You're totally right! 😖
It was a silly mistake to give prefixes and suffixes a color in the first place.
I'll go ahead and take care of this.
