### ISSUE TITLE
Display active python virtual environment

### ISSUE THREAD

**Issue by Pilgrim1379** [matchai/spacefish#146]
How does one enable the display of the current active python virtual environment in the prompt?

**Comment by matchai** [comment]
Hey @thepreacher! Thank you for your interest in having Python virtual environments being added to spacefish.

This is definitely a feature we'd be interested in having added to the project, and we would welcome contributions if you would be interested in contributing. 😄 

Here is the equivalent section file from spaceship, which implements the `venv` section: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/venv.zsh

**Comment by azdanov** [comment]
@matchai Hey! 👋

Don't want to open another issue since these are kinda similar.

I was wondering if making [pipenv](https://github.com/pypa/pipenv#pipenv-python-development-workflow-for-humans) work is somewhat the same?

**Comment by johnfraney** [comment]
@azdanov Both `virtualenv` and `pipenv` set the `$VIRTUAL_ENV` environment variable, which is how [the `pure` fish prompt](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_prompt_virtualenv.fish) provides this functionality.

**Comment by matchai** [comment]
Whoops! Forgot to close this one. 😅
