### ISSUE TITLE
unknown symbol

### ISSUE THREAD

**Issue by prydda** [matchai/spacefish#147]
Didnt find the symbol after the package, what is it? 🤔 
I'm using fira-code-retina if that's any help. 
![image](https://user-images.githubusercontent.com/2561787/51569056-962ff400-1e9b-11e9-8acd-34c954f77b97.png)

**Comment by matchai** [comment]
Hey @prydda! Thanks for opening an issue.

As is documented for the [package section](https://github.com/matchai/spacefish/blob/master/docs/Options.md#package-version-package):
> If no version information is found in package.json, the ⚠ symbol will be shown.

Thanks for using spacefish! 😄
