### ISSUE TITLE
adding duplicate characters

### ISSUE THREAD

**Issue by prydda** [matchai/spacefish#148]
## Bug Report

**Current Behavior**
Whenever I'm typing git remote add it adds by itself "rrreemote" and then I can't remove the duplicate characters. 

**Expected Behavior**
Not adding duplicate characters 

**Relevant `Fish` Configuration**

```fish
My ~/.config/fish/config.fish is empty
```

**Environment**
- Spacefish version: [`2.1.0`]
- Fish version: [`3.0`]
- Fish plugin manager: [oh-my-fish]
- Terminal emulator: [iTerm2]
- Operating system: [OSX 10.14.2]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

![image](https://user-images.githubusercontent.com/2561787/51675278-8adfe400-1fd3-11e9-8473-0eb93b7ef689.png)

**Comment by matchai** [comment]
Hey @prydda!

This is usually caused due to varying character widths between fish-shell and your terminal emulator.

If this issue is caused when using emojis, add the following to your `~/.config/fish/config.fish`:
```fish
set -g fish_emoji_width 2
```

If it is caused by other characters, use the following:
```fish
set -g fish_ambiguous_width 2
```
