### ISSUE TITLE
prompt char disapearing

### ISSUE THREAD

**Issue by prydda** [matchai/spacefish#149]
Im not sure why or how this happends since it's "every now and then" but the theme seems to  bug out all the functioanlity disapears, and enters bash instead of fish.. 

![image](https://user-images.githubusercontent.com/2561787/51682387-96d5a100-1fe7-11e9-8ccd-35fea69dd6e6.png)

**Comment by matchai** [comment]
Hey @prydda! Thanks for opening an issue.
This is actually the deliberate functionality in fish-shell.
Feel free to join the conversation here: https://github.com/fish-shell/fish-shell/issues/904
