### ISSUE TITLE
Tab completion deletes prompt character

### ISSUE THREAD

**Issue by pikeas** [matchai/spacefish#179]
## Bug Report

**Current Behavior**
When pressing `<tab>` to trigger shell completion, the character under the cursor (whether part of the prompt or typed by the user) is deleted.

Here are before/after images to demonstrate:

<img width="244" alt="Screenshot 2019-04-01 16 27 57" src="https://user-images.githubusercontent.com/686573/55365920-45400b80-549b-11e9-8de7-2aa646661843.png">
<img width="241" alt="Screenshot 2019-04-01 16 28 14" src="https://user-images.githubusercontent.com/686573/55365921-45400b80-549b-11e9-9cbc-76036784e79a.png">

Pressing `<tab>` again does not delete additional characters.

**So far, this only seems to happen when the `package` section is present.**

**Expected Behavior**
The character under the cursor should not be deleted.

**Relevant `Fish` Configuration**
```
# I am using the default Spacefish fish_prompt.fish

# config.fish
set -g SPACEFISH_CHAR_SYMBOL "❯"
set -g SPACEFISH_PROMPT_DEFAULT_SUFFIX " "
set -g SPACEFISH_PROMPT_SUFFIXES_SHOW true
set -g SPACEFISH_PROMPT_ORDER package
```

**Environment**
- Spacefish version: 2.4.0
- Fish version: 3.02
- Fish plugin manager: 
- Terminal emulator: iTerm
- Operating system: OSX 10.14.2

**Comment by matchai** [comment]
Hey @pikeas!
Thank you for opening an issue. 😄

Unfortunately I'm having no luck reproducing the issue as described. Would you be able to provide a screen recording using asciicinema of the issue occurring so we can get a better idea of what is happening?

**Comment by pikeas** [comment]
@matchai Thanks for the quick reply! Here's a recording: https://asciinema.org/a/PGuwaFqRyQ2OzmuIQCDZtn99B

Please let me know if you'd like any additional information about my environment. After the above video, I removed `package` from my prompt, sourced my config file, and the bug was gone.

**Comment by matchai** [comment]
@pikeas does the issue occur when using a multi-line prompt? (e.g. having `line-sep` in `SPACEFISH_PROMPT_ORDER`)
I'm thinking it may be an issue with the character width of the emoji on the same line as the prompt which may be causing the issue.

If the issue doesn't occur when the prompt is on the next line, make sure you're using iTerm2 v3 and in **Preferences > Profiles > Text**, use the following settings:

![image](https://user-images.githubusercontent.com/4658208/55367463-2a7d8f00-54bb-11e9-9566-877c6a9767b2.png)


Then, add the following to your fish config:
```fish
# Set the emoji character width
set -g fish_emoji_width 2
```

**Comment by pikeas** [comment]
That did the trick! I already had `Use Unicode version 9 widths` enabled, but did not have `fish_emoji_width` set. Thanks!

**Comment by matchai** [comment]
No problem. Glad that solved it! 😄
