### ISSUE TITLE
Fish color theme to match the one from Spacefish

### ISSUE THREAD

**Issue by cig0** [matchai/spacefish#184]
## Feature Request

Hi all, I'm not sure this is the best place to ask for something _related to_ Spacefish, but not directly involved with it -- please let me know where to head if so!

I find Fish default color theme (configurable using fish_config) hard to read, and honestly don't like the other ones shipped built-in; it would be awesome if someone from the Spacefish community with the correct skills could create a theme matching Spacefish =)

As you see, a super important request this one of mine 🤓 

Thanks

**Comment by matchai** [comment]
Unfortunately, I don't think color schemes are in scope for spacefish.

You may want to look at changing the colors used in your terminal emulator. Here are some examples from the spaceship project: https://github.com/denysdovhan/spaceship-prompt/wiki/Screenshots

I personally use the following color configuration with fish:
```fish
# Fish syntax highlighting
set -g fish_color_autosuggestion '555'  'brblack'
set -g fish_color_cancel -r
set -g fish_color_command --bold
set -g fish_color_comment red
set -g fish_color_cwd green
set -g fish_color_cwd_root red
set -g fish_color_end brmagenta
set -g fish_color_error brred
set -g fish_color_escape 'bryellow'  '--bold'
set -g fish_color_history_current --bold
set -g fish_color_host normal
set -g fish_color_match --background=brblue
set -g fish_color_normal normal
set -g fish_color_operator bryellow
set -g fish_color_param cyan
set -g fish_color_quote yellow
set -g fish_color_redirection brblue
set -g fish_color_search_match 'bryellow'  '--background=brblack'
set -g fish_color_selection 'white'  '--bold'  '--background=brblack'
set -g fish_color_user brgreen
set -g fish_color_valid_path --underline
```
