### ISSUE TITLE
Implement a prompt section for Vagrant status

### ISSUE THREAD

**Issue by ghost** [matchai/spacefish#186]
## Feature Request
Showing the Vagrant status in prompt

**Solution**
Showing the Vagrant VM status if a `Vagrantfile` is in this directory with the command
```vagrant status```

**Comment by matchai** [comment]
Spacefish aims to achieve feature-parity with [spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt/), the original prompt that this is a port of. I suggest new feature proposals be made at the spaceship repo, so that we can port it to spacefish when it gets approved. 🙂
