### ISSUE TITLE
Installation destroys existing custom prompt

### ISSUE THREAD

**Issue by Odaeus** [matchai/spacefish#199]
## Bug Report

**Current Behavior**
Installing Spacefish, in my case via `fisher`, seems to irreversibly overwrite the following files in `.config/fish/functions/`:
* `fish_prompt.fish`
* `fish_left_prompt.fish`
* `fish_right_prompt.fish`

This results in data loss if the user already has custom content in those files.

**Expected Behavior**
Not to overwrite files without warning.

**Environment**
- Spacefish version: 2.6.1
- Fish version: 2.7.1
- Fish plugin manager: fisher
- Terminal emulator: iTerm
- Operating system: Ubuntu

**Possible Solution**
There are many options, perhaps the simplest would be to put a warning at the top of the Install section of the README that this will happen.

More complicated solutions would be:
* Asking the user if they want these files to be overwritten during installation.
* Copying the files with a backup suffix before writing.
* Commenting out the existing contents before writing.

Regards,
Andrew

**Comment by matchai** [comment]
Hey Andrew. Thanks for opening an issue!

The process by which files are overwritten in this case is entirely determined by the plugin manager (fisher, in this case).

I would suggest you create this issue on [their repo](https://github.com/jorgebucaran/fisher), as they would be able to warn the user when installing plugins. They would also be able to provide support for backups to be made of your prompt before it is overwritten by a plugin being installed.

Cheers! 😄
