### ISSUE TITLE
Implement prompt section for hostname

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#20]
## Feature Description
This feature is implemented once we have reached feature parity with the following zsh section: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/host.zsh

## Expected Behaviour

- Reach feature and configuration parity with the implementation in spaceship-prompt
- By default, only show the hostname when there is an SSH connection

**Comment by Snuggle** [comment]
Does this file need to be converted to fish? That doesn't seem hard and hostname is a very useful feature.

**Comment by matchai** [comment]
@Snuggle It sure does! 😄
You're welcome to give it a shot if this feature is valuable to you.

**Comment by matchai** [comment]
Taken care of in #49.
Thank you for your help @Snuggle! 🎉
