### ISSUE TITLE
How to customize prompt with Vi mode?

### ISSUE THREAD

**Issue by Kevin-Mok** [matchai/spacefish#201]
I copied the default prompt order [from the docs](https://github.com/matchai/spacefish/blob/master/docs/Options.md#order), but the Vi mode indicator disappears as soon as I put these lines into my `config.fish`:

```
set SPACEFISH_PROMPT_ORDER time user dir host git package node docker ruby golang php rust haskell julia aws conda pyenv kubecontext exec_time line_sep battery jobs exit_code char
set SPACEFISH_VI_MODE_SHOW true
```

If I remove those lines, the indicator comes back. So, how do I customize the prompt while still keeping the indicator?

**Comment by matchai** [comment]
Hey Kevin!
The reason the indicator disappears when you add those lines is because your `SPACEFISH_PROMPT_ORDER` is missing the `vi_mode` segment, which is included in the prompt order by default.

From there, you can proceed to modify the following configuration values:
```
set SPACEFISH_VI_MODE_SHOW true
set SPACEFISH_VI_MODE_PREFIX " "
set SPACEFISH_VI_MODE_SUFFIX $SPACEFISH_PROMPT_DEFAULT_SUFFIX
set SPACEFISH_VI_MODE_INSERT [I]
set SPACEFISH_VI_MODE_NORMAL [N]
set SPACEFISH_VI_MODE_VISUAL [V]
set SPACEFISH_VI_MODE_REPLACE_ONE [R]
set SPACEFISH_VI_MODE_COLOR white
```
