### ISSUE TITLE
iTerm2 instructions for displaying overlapping emojis properly are wrong

### ISSUE THREAD

**Issue by ohcibi** [matchai/spacefish#208]
The readme recommends for [iterm2 users](https://github.com/matchai/spacefish/blob/master/docs/Troubleshooting.md#why-do-my-section-icons-overlap-each-other):

> ...
> Check Threat ambiguous-width characters as double-width.
> ...

As it is explained right at that setting, checking this is recommended only for users that mostly work with east asian languages and that it can cause misalignment for most other users which is exactly the case. Besides causing misalignments that are so severe that one cannot use the prompt anyways, that option doesn't even solve the issue with overlapping symbols. The only real workaround that works for me in iTerm2 is to add extra spaces to every ambiguous character in my prompt.

**Comment by matchai** [comment]
I've removed mention of enabling "ambiguous-width characters as double-width". 👍
