### ISSUE TITLE
Slow loading on macOS Catalina

### ISSUE THREAD

**Issue by dalisoft** [matchai/spacefish#211]
## Bug Report

**Current Behavior**
`fish-shell` loading very slow or never (sometimes, most of time slow loading times)

**Expected Behavior**
It should load fast as default theme

**Relevant `Fish` Configuration**

```fish
set -g fish_user_paths "/usr/local/sbin" $fish_user_paths
```

**Environment**
- Spacefish version: [the output of `echo $SPACEFISH_VERSION`]: 2.7.0
- Fish version: [the output of `fish --version`]: fish, version 3.0.2
- Fish plugin manager: [e.g. oh-my-fish, fisher, fin]: oh-my-fish
- Terminal emulator: [e.g. iTerm, Hyper, Terminator]: iTerm
- Operating system: [e.g. OSX 10.13.4, Windows 10]: macOS Catalina 10.15.1 (Latest update)

**Possible Solution**
If Docker (Dinghy) enabled, loads fast. When disabled very sloow.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

Related issue: https://github.com/fish-shell/fish-shell/issues/6408

**Comment by dalisoft** [comment]
Setting `set -g SPACEFISH_DOCKER_SHOW false` in config helped for me.
I sure, if it matches `docker-compose.yml` in folder, waiting for Docker for version.

**Comment by matchai** [comment]
Hi @dalisoft. Thank you for opening an issue.
Unfortunately, spacefish is no longer under active development, but I suggest you take a look at its successor https://github.com/starship/starship, which has considerably faster loading times.

That said, if someone comes around with a PR to fix this bug, I'll gladly review and merge it. 😄

**Comment by dalisoft** [comment]
Thanks for response. Currently passing env is workaround. Starship also does not have Docker support, so seem removing that little faster, but cannot replace this awesome shell prompt/theme. 

We can close this issue, workaround have, but I don’t have time to PR (sorry)
