### ISSUE TITLE
command color

### ISSUE THREAD

**Issue by kort3x** [matchai/spacefish#218]
Hi,

how do I change the color of commands/programs? It's dark blue fro me and honestly I have no clue why, sorry.

![image](https://user-images.githubusercontent.com/13918530/86539719-30a0bd80-beff-11ea-83f3-45cc51bd35e5.png)

**Comment by matchai** [comment]
Hi @kort3x,
Spacefish should have no effect on the way the commands look as you type them. The command colors can be configured using the `fish_color_*` environment variables listed here: https://fishshell.com/docs/current/#variables-color

**Comment by kort3x** [comment]
> Hi @kort3x,
> Spacefish should have no effect on the way the commands look as you type them. The command colors can be configured using the `fish_color_*` environment variables listed here: https://fishshell.com/docs/current/#variables-color

Thanks!
