### ISSUE TITLE
.git directory and subsequent folders do not show

### ISSUE THREAD

**Issue by tiffafoo** [matchai/spacefish#22]
# Bug
## Expected Behaviour
Expected `.git` and inner directories names to be shown in the terminal, in the space where the current directory name is normally displayed.

## Actual Behaviour
Instead we have an empty space as shown in this screenshot:
<img width="394" alt="screen shot 2018-03-05 at 12 27 25 am" src="https://user-images.githubusercontent.com/11183523/36958752-0b46f49e-200c-11e8-9bd4-feadc00e39ec.png">

## Reproduction Steps
```bash
➜ mkdir coolest-repo
➜ cd coolest-repo
➜ git init
➜ cd .git
```
The behavior can be seen here. You can also see that going further in (i.e.: `cd hooks`) will continue the issue. `cd`-ing out of `git` solves it.

## Probable Cause
Most likely the cause is the from one of the fish files that deal with git (i.e. `spacefish/functions/__sf_section_git.fish`)

**Comment by matchai** [comment]
It looks like the error occurs at this line: https://github.com/matchai/spacefish/blob/master/functions/__sf_section_dir.fish#L26
When attempting to get the root folder of a git repo, the command fails while in the `.git` directory or its subdirectories.

**Comment by matchai** [comment]
One solution I've found is that `git rev-parse --absolute-git-dir` provide the `.git` directory from any location within the repo.

Instead of using `git rev-parse --show-toplevel`, we could use `git rev-parse --absolute-git-dir` and trim the `/.git`.

![image](https://user-images.githubusercontent.com/4658208/37040548-21e2a5c8-2128-11e8-8a86-7469bff88ab7.png)

**Comment by matchai** [comment]
All future discussion of this issue will take place in the same issue on spaceship's repo: https://github.com/denysdovhan/spaceship-prompt/issues/388

**Comment by matchai** [comment]
Due to #45, this issue has been reopened.
We may not be able to correctly truncate the directory to the git project root, but at the very least we should be showing the directory name.
