### ISSUE TITLE
Implement prompt section for background jobs

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#32]
## Feature Description
This feature is implemented once we have reached feature parity with the following zsh section: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/jobs.zsh

## Expected Behaviour

- Reach feature and configuration parity with the implementation in spaceship-prompt
- Show indicator when there are background jobs
- Show counter where there are multiple background jobs

**Comment by Snuggle** [comment]
A couple MacOS compatibility issues (BSD coreutils weirdness, most likely) were encountered with this section, so it has been dropped from `spacefish-swim-to-v1.0`.

I'll make a new pull request after manually testing and fixing MacOS w̶i̶t̶h̶i̶n̶ ̶a̶ ̶c̶o̶u̶p̶l̶e̶ ̶d̶a̶y̶s̶ ̶o̶r̶ ̶s̶o̶ today.

**Comment by Snuggle** [comment]
Interesting... BSD's word-count util has a more consistent format, but also adds random spaces which borked things for `wc -l`.

![image](https://user-images.githubusercontent.com/26250962/45121360-d09d2c80-b158-11e8-83d6-9e206b34be60.png) ![image](https://user-images.githubusercontent.com/26250962/45121447-14903180-b159-11e8-86b5-a717fbc9fcbf.png)
