### ISSUE TITLE
Implement prompt section for ruby version

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#35]
## Feature Description
This feature is implemented once we have reached feature parity with the following spaceship section: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/ruby.zsh

## Expected Behaviour
- Reach feature and configuration parity with the implementation in spaceship-prompt
- Show ruby version using the following version managers:
	- [x] rvm
	- [x] rbenv
	- [x] chruby
	- [x] asdf

**Comment by avegancafe** [comment]
Are there any other ruby version managers that we should create for this feature to be complete? Assuming `asdf` is a placeholder 😄

**Comment by tiffafoo** [comment]
@kyleholzinger The ruby version managers left are `chruby` and `asdf` (the unchecked boxes above).

`asdf` is indeed real 😆: https://github.com/asdf-vm/asdf

Spacefish implementation reference: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/ruby.zsh#L37

**Comment by avegancafe** [comment]
Hahahah oh man, alright well I'm not familiar with that one but I'll give a shot at `chruby`!

**Comment by avegancafe** [comment]
Were we still thinking of doing asdf? @matchai #46 only did chruby, not sure if that's in the works

**Comment by tiffafoo** [comment]
Yeah `asdf` still open @kyleholzinger. It just closed because when you have an issue preempted by `closes`/`fix`, etc. it closes the issue automatically. Reopened!
