### ISSUE TITLE
Prompt disappears under a window breakpoint

### ISSUE THREAD

**Issue by roginfarrer** [matchai/spacefish#56]
## Bug Report

**Current Behavior**
If the width of the window is under a certain breakpoint, the entire prompt will disappear, and appears broken.

**Expected Behavior**
The prompt should wrap if there's not enough space inline.

**Environment**
- Spacefish version: 0.1.0
- Fish version: 2.7.1
- Fish plugin manager: oh-my-fish
- Terminal emulator: iTerm
- Operating system: OSX 10.13.4

**Additional context/Screenshots**
![Gif of the issue](https://dzwonsemrish7.cloudfront.net/items/442f1C2z1c2z3N3L0N0S/Screen%20Recording%202018-08-02%20at%2002.52%20PM.gif?v=9f316947)

**Comment by matchai** [comment]
Hey @roginfarrer 👋 
Thanks for opening up a ticket!

This is a [deliberate feature](https://github.com/fish-shell/fish-shell/issues/904#issuecomment-21162556) in fish shell itself.

Implementing some breakpoints in spacefish to regress down a more basic version of the shell if the terminal width gets smaller would be a welcome contribution.
