### ISSUE TITLE
"set SPACEFISH_PROMPT_ORDER" fails to apply

### ISSUE THREAD

**Issue by roginfarrer** [matchai/spacefish#57]
## Bug Report

**Current Behavior**
Setting `SPACESHIP_PROMPT_ORDER` or `SPACEFISH_PACKAGE_SHOW` fails to have an affect when saved to `init.fish`. It also does not apply when placed inside `config.fish`.

```fish
set SPACEFISH_PROMPT_ORDER user dir git exec_time line_sep battery jobs char
set SPACEFISH_PACKAGE_SHOW false
```

**Expected Behavior**
Setting the above would change my prompt.

**Environment**
- Spacefish version: 0.1.0
- Fish version: 2.7.1
- Fish plugin manager: oh-my-fish
- Terminal emulator: iTerm
- Operating system: OSX 10.13.4

**Comment by matchai** [comment]
On my local configuration, I've had no problem changing these config values.
https://asciinema.org/a/SXWCSN8IADx5HRZkKKFjvM9is

What about if you set these values outside of a configuration file? Does the prompt display differently if you run these `set` commands directly?

**Comment by roginfarrer** [comment]
Ah, the `-g` was the issue.

Regarding the other command, removing `jobs` also seems to fix it as well. I had brought that over from Spaceship. 

For posterity, this was resolved with the following:

```fish
set -g SPACEFISH_PROMPT_ORDER user dir git exec_time line_sep battery char
set -g SPACEFISH_PACKAGE_SHOW false
```
