### ISSUE TITLE
Spacefish doesn't like Raspberries 🍓

### ISSUE THREAD

**Issue by Snuggle** [matchai/spacefish#59]
## Bug Report

**Current Behavior**
Installing Spacefish using fisherman causes the prompt to be totally unusable and broken due to some errors displaying the git section(s) on my Raspberry Pi Model B rev2.0.

_Most likely a Fish version incompatibility._

**Expected Behavior**
Spacefish should either check Fish version and disable incompatible sections or potentially display a warning about an incompatible version?

**Pastebin**
https://pastebin.com/sE9GgcH7

**Environment**
- Spacefish version: `N/A, non-functional prompt`
- Fish version: `fish v2.4.0`
- Fish plugin manager: `fisherman`
- Terminal emulator: `kitty, over SSH`
- Operating system: `Raspbian 9.4 (stretch) armv6l, kernel 4.14.52+`

**Possible Solution**
It seems to be complaining about line 84 in [__sf_section_git_status.fish.](
https://github.com/matchai/spacefish/blob/bebe300288d6a371ce69806bff382f0ae0d142e8/functions/__sf_section_git_status.fish#L84)

I'm also not exactly sure what the purpose of line 31 in [__sf_section_git.fish](https://github.com/matchai/spacefish/blob/bebe300288d6a371ce69806bff382f0ae0d142e8/functions/__sf_section_git.fish#L31). What's `fff`? Did someone fall asleep on their keyboard? :yum: 

This is most likely a problem with fish <2.7.0.
Sadly v2.4.0 is the latest available version in Raspbian repositories. Perhaps there should be a note in the README.md to not use on Raspbian/Debian, since this fully breaks people's prompt?

Or would it be possible to add a check to disable the git section if an old version of Fish is detected? This would at least prevent people's prompt from breaking.

**Additional context/Screenshots**
Everything is the newest version available for Raspbian. Fresh installation, less than 1 day old.

![image](https://user-images.githubusercontent.com/26250962/43789023-d4f995c4-9a66-11e8-9e6b-d6f853ac134f.png)

**Comment by matchai** [comment]
It appears the `string upper` method is causing the issue, [which was added](https://github.com/fish-shell/fish-shell/issues/4080) in fish 2.7.0.

It appears the latest Fish is available for Debian on the `shells:fish:release:2` repository. Details here: https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish

With regard to [__sf_section_git.fish line 31](https://github.com/matchai/spacefish/blob/bebe300288d6a371ce69806bff382f0ae0d142e8/functions/__sf_section_git.fish#L31), "fff" is the white hexcode, which is used for the bright white color fallback.

I think a fish version check is a good idea, and could be referenced in a standalone issue. 😄
