### ISSUE TITLE
Implement a prompt section for Conda version (🅒)

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#70]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This feature is intended to achieve feature parity with the following Spaceship section file: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/conda.zsh

**Describe the solution you'd like**
Porting over the existing zsh implementation of the Conda section file, showing the current Conda version when a Conda virtual environment is activated.

**Comment by jskrnbindra** [comment]
@matchai Taking up this one as well. 😸

**Comment by matchai** [comment]
Excellent! Glad to have you contributing! 😄

**Comment by jayagami** [comment]
Why not add a section to show conda env verbose, I thought it would be much useful ...
