### ISSUE TITLE
Implement a prompt section for Kubectl version (☸️)

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#73]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This feature is intended to achieve feature parity with the following Spaceship section file: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/kubecontext.zsh

**Describe the solution you'd like**
Porting over the existing zsh implementation of the kubectl section file, showing the current kubectl version when there is a kubernetes context.

**Comment by owais** [comment]
This would be really nice to have :+1:

**Comment by owais** [comment]
@matchai Build it for myself. Maybe it can be upstreamed. https://github.com/matchai/spacefish/pull/76
