### ISSUE TITLE
Implement a prompt section for Vi mode

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#74]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This feature is intended to achieve feature parity with the following Spaceship section file: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/vi_mode.zsh

**Describe the solution you'd like**
Porting over the existing zsh implementation of the Vi mode section file, indicating whether or not the shell is set to Vi mode, which is enabled with `fish_vi_key_bindings`.

Useful discussion on fish vi bindings can be found here: https://github.com/fish-shell/fish-shell/issues/3232

**Comment by kulabun** [comment]
I guess we can close this ?

**Comment by matchai** [comment]
Oh! Yes we can.
Thank you. 👍
