### ISSUE TITLE
Add "write permission" feature to dir section

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#75]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This feature is intended to add the feature enhancement added to the dir section in the following two PRs:
https://github.com/denysdovhan/spaceship-prompt/pull/340
https://github.com/denysdovhan/spaceship-prompt/pull/517

**Describe the solution you'd like**
Porting over the existing zsh functionality of displaying write permissions in the dir section file that was added in this commit: https://github.com/denysdovhan/spaceship-prompt/commit/a5d5d31aee54a00833b1f7114793290038d4e00f

**Comment by jskrnbindra** [comment]
Working on this.
