### ISSUE TITLE
Implement a prompt section for Docker version (🐳)

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#84]
## Feature Request

**Is your feature request related to a problem? Please describe.**
This feature is intended to achieve feature parity with the following Spaceship section file: https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/docker.zsh

**Describe the solution you'd like**
Porting over the existing zsh implementation of the Docker section file, showing the current Docker version and machine name when the prompt is in the same directory as a `Dockerfile`, `docker-compose.yml` or a compose file.

**Comment by jskrnbindra** [comment]
@matchai I would like to do this one.
Will open a PR soon..!

**Comment by matchai** [comment]
Perfect!
Looking forward to seeing your PR @jskrnbindra. 😄

**Comment by jskrnbindra** [comment]
Hey @matchai I have a question.
Once I make any changes (say: add docker section), How do I test it (not talking about the tests/)? I mean how do I get the theme (with my changes) loaded into my terminal?

**Comment by matchai** [comment]
You should be able to install it with your fish package manager by providing a relative path to your local project. 
```
fisher add ./
```

**Comment by jskrnbindra** [comment]
@matchai  I'm getting the following error. Am I missing something obvious? 🤔

```bash
fetching https://codeload.github.com/./tar.gz/master
rm: "." and ".." may not be removed
cannot install github.com/. -- is this a valid package?
added 1 package in 1.38s
```

**Comment by matchai** [comment]
I believe it might be because you ran `fisher add .` rather than `fisher add ./` 😜 
That should probably be an issue opened in Fisher. I ran into the same issue the other day.

**Comment by jskrnbindra** [comment]
I tried both. Same result. :/

**Comment by matchai** [comment]
Huh... How about providing the full path to the project directory?
`fisher add ./` works fine for me locally, but `fisher ls` shows the full path to the project.
https://asciinema.org/a/UwKKqqZJ3QYPrkPdNEdIP8EN3

Make sure fisher is running the latest version with `fisher self-update`. A new major version of fisher was just released last week, so there's bound to be some quirky behavior.

**Comment by jskrnbindra** [comment]
Oh yes! Giving the full path instead of ```./``` works for me.
Thanks. 😊
